core_admin:
    resource: "@CoreAdminBundle/Resources/config/routing.yml"
    prefix:   /

core_security:
    resource: "@CoreSecurityBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
