_core_security_homepage:
    path:     /hello/{name}
    defaults: { _controller: CoreSecurityBundle:Default:index }	
core_security_homepage:
    path:     /
    defaults: { _controller: CoreSecurityBundle:Default:index }